/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mikiller_ndktest_ndkapplication_NDKImpl */
#include <string.h>
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mikiller_ndktest_ndkapplication_NDKImpl
 * Method:    helloWorld
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mikiller_ndktest_ndkapplication_NDKImpl_helloWorld
  (JNIEnv *, jobject, jstring);



#ifdef __cplusplus
}
#endif
