/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mikiller_ndktest_ndkapplication_NDKImpl */

#ifndef _Included_com_mikiller_ndktest_ndkapplication_NDKImpl
#define _Included_com_mikiller_ndktest_ndkapplication_NDKImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mikiller_ndktest_ndkapplication_NDKImpl
 * Method:    initFFMpeg
 * Signature: (Ljava/lang/String;IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mikiller_ndktest_ndkapplication_NDKImpl_initFFMpeg
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mikiller_ndktest_ndkapplication_NDKImpl
 * Method:    pushAudio
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_mikiller_ndktest_ndkapplication_NDKImpl_pushAudio
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_mikiller_ndktest_ndkapplication_NDKImpl
 * Method:    pushVideo
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_com_mikiller_ndktest_ndkapplication_NDKImpl_pushVideo
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_mikiller_ndktest_ndkapplication_NDKImpl
 * Method:    initTS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mikiller_ndktest_ndkapplication_NDKImpl_initTS
  (JNIEnv *, jclass);

/*
 * Class:     com_mikiller_ndktest_ndkapplication_NDKImpl
 * Method:    flush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mikiller_ndktest_ndkapplication_NDKImpl_flush
  (JNIEnv *, jclass);

/*
 * Class:     com_mikiller_ndktest_ndkapplication_NDKImpl
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mikiller_ndktest_ndkapplication_NDKImpl_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
